version: '3'

services:
    $DOMAIN_FILE-dbserver:
        container_name: $DOMAIN_FILE-$DB_container_name
        image: $DB_image
        environment:
            MYSQL_ROOT_PASSWORD: $DB_pass
        ports:
            - $DB_portOut:$DB_portIn
        volumes:
            - $DB_volumePath
        restart: always
        labels:
            - "CONF_GROUP=$CONF_GROUP"
        networks:
            - proxy

    webserver:
        container_name: $DOMAIN_FILE-$WP_container_name
        image: $WP_image
        links:
            - $DOMAIN_FILE-dbserver:mysql
        ports:
            - $WP_portOut:$WP_portIn
        expose:
            - $WP_portOut
        volumes:
            - $WP_volumePath
        restart: always
        labels:
            - "CONF_GROUP=$CONF_GROUP"
        environment:
            WORDPRESS_DEBUG: $WP_debug
            WORDPRESS_DB_HOST: $DOMAIN_FILE-dbserver
            WORDPRESS_DB_USER: $DB_user
            WORDPRESS_DB_NAME: $DB_name
            WORDPRESS_DB_PASSWORD: $DB_pass
            VIRTUAL_HOST: $HOST_domainsDeclaration
            LETSENCRYPT_HOST: $HOST_domainsDeclaration
            LETSENCRYPT_EMAIL: hubert.sobkow@gmail.com
        networks:
            - proxy

networks:
    proxy:
        external: true
