version: '3'

services:
    dbserver:
        container_name: $DOMAIN_FILE-$DB_container_name
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: $DB_pass
        ports:
            - $DB_portOut:$DB_portIn
        volumes:
            - $DB_volumePath
        restart: always
        networks:
            - proxy

    webserver:
        container_name: $DOMAIN_FILE-$WP_container_name
        image: $WP_image
        links:
            - dbserver:mysql
        ports:
            - $WP_portOut:$WP_portIn
        expose:
            - $WP_portOut
        volumes:
            - $WP_volumePath
        restart: always
        environment:
            WORDPRESS_DB_HOST: $DB_host
            WORDPRESS_DB_USER: $DB_user
            WORDPRESS_DB_NAME: $DB_name
            WORDPRESS_DB_PASSWORD: $DB_pass
            VIRTUAL_HOST: $HOST_domainsDeclaration
            LETSENCRYPT_HOST: $HOST_domainsDeclaration
            LETSENCRYPT_EMAIL: hubert.sobkow@gmail.com
        networks:
            - proxy

networks:
    proxy:
        external: true