version: '3'

services:
    $DOMAIN_FILE-dbserver:
        container_name: $DOMAIN_FILE-$DB_container_name
        image: $DB_image
        environment:
            MYSQL_ROOT_PASSWORD: $DB_pass
        ports:
            - $DB_portOut:$DB_portIn
        volumes:
            - $DB_volumePath
            - $DB_confPath
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        labels:
            - "CONF_GROUP=$CONF_GROUP"
            - "wpdeployer.site=$DOMAIN_FILE"
            - "wpdeployer.service=mariadb"
            - "wpdeployer.logs=$LOGS_enabled"
        networks:
            - proxy

    webserver:
        container_name: $DOMAIN_FILE-$WP_container_name
        image: $WP_image
        links:
            - $DOMAIN_FILE-dbserver:mysql
        ports:
            - $WP_portOut:$WP_portIn
        expose:
            - $WP_portOut
        volumes:
            - $WP_volumePath
            - $WP_apacheConfPath
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        labels:
            - "CONF_GROUP=$CONF_GROUP"
            - "wpdeployer.site=$DOMAIN_FILE"
            - "wpdeployer.service=wordpress"
            - "wpdeployer.logs=$LOGS_enabled"
        environment:
            WORDPRESS_DEBUG: "$WP_debug"
            WORDPRESS_CONFIG_EXTRA: "$WP_configExtra"
            WORDPRESS_DB_HOST: $DOMAIN_FILE-dbserver
            WORDPRESS_DB_USER: $DB_user
            WORDPRESS_DB_NAME: $DB_name
            WORDPRESS_DB_PASSWORD: $DB_pass
            VIRTUAL_HOST: $HOST_domainsDeclaration
            LETSENCRYPT_HOST: $HOST_domainsDeclaration
            LETSENCRYPT_EMAIL: hubert.sobkow@gmail.com
        networks:
            - proxy

networks:
    proxy:
        external: true
