version: '3'

services:
  logger:
    image: docker:cli
    container_name: wpdeployer-logger
    restart: always
    entrypoint: ["/bin/sh", "/collector.sh"]
    environment:
      - LOGROOT=/volumes
      - RETENTION_DAYS=${LOGS_retentionDays:-7}
      - MAX_SIZE_MB=${LOGS_maxSizeMB:-500}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${WPDEPLOYER_VOLUMES:-../../volumes}:/volumes
      - ./collector.sh:/collector.sh:ro
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
