version: '3'

services:
    webserver:
        container_name: biolafit.pl-wordpress
        image: wordpress
        links:
            - dbserver:mysql
        ports:
            - 81:80
        expose:
            - 81
        volumes:
            - /root/wpdeployer/volumes/biolafit.pl/wordpress:/var/www/html
        restart: always
        environment:
            WORDPRESS_DB_HOST: dbserver
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_NAME: mysql
            WORDPRESS_DB_PASSWORD: 31A2950F9E0AD1DE7CEBF92B5ADFDE5B49738E558931852B55EEF13CE892FBD7
            VIRTUAL_HOST:  biolafit.pl, www.biolafit.pl
            LETSENCRYPT_HOST:  biolafit.pl, www.biolafit.pl
            LETSENCRYPT_EMAIL: hubert.sobkow@gmail.com

    dbserver:
        container_name: biolafit.pl-mariadb
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: 31A2950F9E0AD1DE7CEBF92B5ADFDE5B49738E558931852B55EEF13CE892FBD7
        ports:
            - 3301:3306
        volumes:
            - /root/wpdeployer/volumes/biolafit.pl/mariadb:/var/lib/mysql
        restart: always

networks:
    default:
        external:
            name: proxy
